USE TWDemo;

SELECT * FROM grade;
SELECT * FROM student LIMIT 19,11;
SELECT * FROM course LIMIT 19,11;
SELECT * FROM teacher LIMIT 19,11;
SELECT * FROM student_course LIMIT 19,11;
SELECT * FROM teacher_course LIMIT 19,11;
SELECT * FROM schedule LIMIT 19,11;
